# EXIF Tag名の日本語対応マッピング
# フォーマット: tag_id: 日本語名
exif_tags:
  271: "メーカー"
  272: "モデル"
  274: "画像の向き"
  282: "X解像度"
  283: "Y解像度"
  296: "解像度単位"
  306: "撮影日時"
  315: "作成者"
  33434: "露出時間"
  33437: "F値"
  34850: "露出プログラム"
  34855: "ISO感度"
  36864: "Exifバージョン"
  36867: "撮影日時"
  36868: "デジタル化日時"
  37121: "色空間の構成要素"
  37377: "シャッタースピード値"
  37378: "絞り値"
  37379: "明度値"
  37380: "露出補正値"
  37381: "最大絞り値"
  37382: "被写体距離"
  37383: "測光方式"
  37384: "光源"
  37385: "フラッシュ"
  37386: "焦点距離"
  37396: "被写体エリア"
  40960: "FlashPixバージョン"
  40961: "色空間"
  40962: "ピクセルX寸法"
  40963: "ピクセルY寸法"
  41486: "ホワイトバランス"
  41487: "デジタルズーム倍率"
  41488: "35mm換算焦点距離"
  41489: "シーンキャプチャタイプ"
  41490: "ゲインコントロール"
  41491: "コントラスト"
  41492: "彩度"
  41493: "シャープネス"
  41495: "被写体距離範囲"
  42016: "画像ユニークID"

# 画像の向きの値マッピング
orientation_values:
  1: "正常"
  2: "水平反転"
  3: "180度回転"
  4: "垂直反転"
  5: "90度反時計回りに回転後水平反転"
  6: "90度時計回りに回転"
  7: "90度時計回りに回転後水平反転"
  8: "90度反時計回りに回転"

# 色空間の値マッピング
color_space_values:
  1: "sRGB"
  2: "Adobe RGB"
  65535: "未較正"

# 測光方式の値マッピング
metering_mode_values:
  0: "不明"
  1: "平均"
  2: "中央重点"
  3: "スポット"
  4: "マルチスポット"
  5: "パターン"
  6: "部分"
  255: "その他"

# 光源の値マッピング
light_source_values:
  0: "不明"
  1: "昼光"
  2: "蛍光灯"
  3: "タングステン"
  4: "フラッシュ"
  9: "晴天"
  10: "曇天"
  11: "日陰"
  12: "昼光色蛍光灯"
  13: "昼白色蛍光灯"
  14: "白色蛍光灯"
  15: "温白色蛍光灯"
  17: "標準光A"
  18: "標準光B"
  19: "標準光C"
  20: "D55"
  21: "D65"
  22: "D75"
  23: "D50"
  24: "ISO スタジオタングステン"
  255: "その他"

# ホワイトバランスの値マッピング
white_balance_values:
  0: "オート"
  1: "マニュアル"

# シーンキャプチャタイプの値マッピング
scene_capture_type_values:
  0: "標準"
  1: "風景"
  2: "ポートレート"
  3: "夜景"

# コントラスト/彩度/シャープネスの値マッピング
enhancement_values:
  0: "標準"
  1: "ソフト"
  2: "ハード"

# 被写体距離範囲の値マッピング
subject_distance_range_values:
  0: "不明"
  1: "マクロ"
  2: "近景"
  3: "遠景"